tag_prefix = "v"

post_bump_hooks = [
    # "git push origin v{{version}}",
    # "npm version {{version}}",
    # "git push",
    "gh release create {{version}} -d -t Version {{version}} -n $(cog changelog v{{version}})"
]
