name: '🚀 Release (Next)'
on:
  push:
    branches: main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install
        run: npm ci
      - name: Bump
        # TODO: replace once 3 is stable and published
        # run: npm version prerelease --preid=next.$(git rev-parse --short HEAD) --no-git-tag-version --no-push
        run: npm version 3.0.0-next.$(git rev-parse --short HEAD) --no-git-tag-version --no-push

      - name: Publish
        run: npm publish --dist-tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}