name: '🚀 Release (Next)'
on:
  push:
    branches: main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install & Bump
        run: |
          npm ci
          npm version prerelease --preid=next.${git rev-parse --short HEAD} --no-git-tag-version --no-push
      - name: Release
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: publish from-package --yes --dist-tag canary