name: '🚀 Release'

on:
  workflow_dispatch:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    name: Perform release

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cocogitto release
        id: release
        uses: oknozor/cocogitto-action@main
        with:
          release: true
          check-latest-tag-only: true
